version: "3"
services: 
    proxy:
        # build: 
        #     context: ./nginx
        #     dockerfile: nginx
        image: nginx
        ports: 
            - "80:80"
        restart: always
    client:
        # build:
        #     context: ./FileSharingApp.UI
        #     dockerfile: angular-app
        image: angular-app
        ports: 
            - "9000:80"
    api:
        # build: 
        #     context: ./FileSharingApp.API
        #     dockerfile: web-api
        image: web-api
        ports: 
            - "5000:80"